import { Station, Facility } from "@/types/domain";

export const MOCK_STATIONS: Station[] = [
  {
    id: 1,
    station_code: "1130206",
    organization_code: "2",
    line_name: "JR中央線",
    name: "高円寺",
    prefecture_code: 13,
    location: "POINT(139.649664 35.705333)",
    total_score: 92,
    rent_avg: 8.8,
    score_details: {
      access: 90,
      rent: 85,
      facility: 95,
      safety: 70,
      disaster: 80,
    },
    address: "東京都杉並区高円寺南四丁目",
    lines: [
      { id: 101, station_id: 1, line_name: "JR中央線" },
      { id: 102, station_id: 1, line_name: "JR総武線" },
    ],
    is_nearby: true,
    stops_from_source: 0,
  },
  {
    id: 2,
    station_code: "1130207",
    organization_code: "2",
    line_name: "JR中央線",
    name: "中野",
    prefecture_code: 13,
    location: "POINT(139.665805 35.705791)",
    total_score: 88,
    rent_avg: 9.5,
    score_details: {
      access: 95,
      rent: 75,
      facility: 98,
      safety: 80,
      disaster: 75,
    },
    address: "東京都中野区中野五丁目",
    lines: [
      { id: 201, station_id: 2, line_name: "JR中央線" },
      { id: 202, station_id: 2, line_name: "JR総武線" },
      { id: 203, station_id: 2, line_name: "東京メトロ東西線" },
    ],
    is_nearby: true,
    stops_from_source: 1,
  },
  {
    id: 3,
    station_code: "1130205",
    organization_code: "2",
    line_name: "JR中央線",
    name: "阿佐ヶ谷",
    prefecture_code: 13,
    location: "POINT(139.635868 35.704875)",
    total_score: 85,
    rent_avg: 8.2,
    score_details: {
      access: 85,
      rent: 90,
      facility: 88,
      safety: 85,
      disaster: 82,
    },
    address: "東京都杉並区阿佐谷南三丁目",
    lines: [
      { id: 301, station_id: 3, line_name: "JR中央線" },
      { id: 302, station_id: 3, line_name: "JR総武線" },
    ],
    is_nearby: true,
    stops_from_source: 1,
  },
];

export const MOCK_FACILITIES: Facility[] = [
  {
    id: "f1",
    name: "OK Store 高円寺店",
    category: "supermarket",
    distance_meters: 250,
    rating: 4.2,
    lat: 35.703,
    lon: 139.648,
  },
  {
    id: "f2",
    name: "セブンイレブン 高円寺南4丁目店",
    category: "convenience",
    distance_meters: 80,
    rating: 3.5,
    lat: 35.704,
    lon: 139.65,
  },
  {
    id: "f3",
    name: "馬橋公園",
    category: "park",
    distance_meters: 500,
    rating: 4.5,
    lat: 35.708,
    lon: 139.645,
  },
];
